### ISSUE TITLE
prometheus metrics not shown up

### ISSUE THREAD

**Issue by siad007** [hellofresh/kandalf#71]
# How to reproduce
- Use kandalf with prometheus

# Expected behaviour
- See metrics

# Actual behaviour
- No metrics

I have a problem using kandalf with prometheus metrics. Is it working at all or did I use the wrong port maybe?

I have tried with:

* set `STATS_DSN` env to `prometheus://test`
* start kandalf
* browse to `http://localhost:8080/metrics`

with no luck.

Maybe I use the wrong port for prometheus scraping?

**Comment by siad007** [comment]
@vgarvardt Glad to see your fix on this issue - is there any new release planned with it on your side?

**Comment by vgarvardt** [comment]
Just released https://github.com/hellofresh/kandalf/releases/tag/0.8.0
